# Generated by Django 5.1.7 on 2025-03-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_departm_cfdfa6_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
    ]
