# Generated by Django 5.1.7 on 2025-03-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='department',
        ),
    ]
